[tool.black]
line-length = 80

[tool.isort]
profile = "black"
line_length = 80
order_by_type = false
combine_as_imports = true
force_sort_within_sections = true
import_heading_stdlib = "Standard"
import_heading_thirdparty = "Third party"
import_heading_firstparty = "Atomwise"
extra_standard_library = ["__main__"]

[tool.pyright]
exclude = ["bazel-*"]
